### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by DeusHyper** [YoungFellow-le/photoshop-22-linux#11]
### A clear description of the bug:
When I try to start Photoshop, it tells me that there is no file or directory so it doesn't start. The installer runs fine without any problems.

### The output :
```
[jonas@System photoshop-22-linux]$ bash -c '/home/jonas/photoshop-22-linux/scripts/launcher.sh'
/home/jonas/photoshop-22-linux/scripts/launcher.sh: line 2: cd: /home/jonas/photoshop-22-linux/Ps-prefix/drive_c/Program Files/Adobe/Adobe Photoshop 2021/: No such file or directory
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0088:fixme:wineusb:add_usb_device Interface 2 has 3 alternate settings; using the first one.
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:wineusb:query_id Unhandled ID query type 0x5.
0084:fixme:wineusb:query_id Unhandled ID query type 0x5.
0084:fixme:wineusb:query_id Unhandled ID query type 0x5.
0084:fixme:wineusb:query_id Unhandled ID query type 0x5.
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

```

### System info:
 - **Arch Linux**
 - **qtile**
 - **wine-7.19**

**Comment by YoungFellow-le** [comment]
Hello there,
It looks like the Photoshop files haven't been copied to the directory, if it has been downloaded at all.

Please post the output of:
```sh
ls /home/jonas/photoshop-22-linux/Ps-prefix/drive_c/Program Files/Adobe/
```

**Comment by DaanKorver** [comment]
Had the same issue, Adobe folder is empty

**Comment by YoungFellow-le** [comment]
That means that the Adobe files weren't downloaded.
Can you try running the installer again and providing the output?

**Comment by Savuth-S** [comment]
Do you have gdown installed? Its a python package and the script uses that to download the photoshop file, but if its not installed it shows a small error message and proceeds configuring the rest of the wine-prefix drowning that message where it cant find gdown.

@YoungFellow-le I'd suggest you add a check and if gdown its not installed it completely stops the installation process, assuming they're having the same issue I had that should be the fix.

**Comment by YoungFellow-le** [comment]
That's on the TODO list, but I'm kind of busy at the moment.
You can do it if you want, just fork the repo, and edit the script if you have experience in bash.
And I'll assist you on the way.
Otherwise I'll have to find some spare time to enable this feature.

**Comment by YoungFellow-le** [comment]
Please make sure you have all the dependencies installed.
To update the repo's code, run the following command inside the repo:
```
git pull
```
