### ISSUE TITLE
Installer says dependencies are missing -- they're not

### ISSUE THREAD

**Issue by Vermoot** [YoungFellow-le/photoshop-22-linux#12]
Hi there!
I'm trying to use your installer, and it fails, saying every dependency is missing. I've installed gdown with `pip3 install` and checked every other dependency was indeed installed, and they definitely are.
Here's a screenshot.
![image](https://user-images.githubusercontent.com/23317434/200294380-1dd02168-5044-4ed2-9946-d309f0b7404e.png)

I'm on Arch (btw). Current version of wine is `wine-7.20 (Staging)`, though I don't thing it matters at this stage.

Any clue what I could do to fix this? Thanks!

**Comment by YoungFellow-le** [comment]
I forgot to add the ! to denote the exception, Sorry.
Give me a minute to fix it.

**Comment by YoungFellow-le** [comment]
Just fixed the issue, please update the code by running:
```
git pull
```

Sorry for the inconvenience.

**Comment by Vermoot** [comment]
> Sorry for the inconvenience.

Mate, I posted an issue and you fixed it within 5 minutes. You have nothing to apologize for :D Cheers!

**Comment by YoungFellow-le** [comment]
Let me know if it works.

**Comment by Vermoot** [comment]
Yes it did
