### ISSUE TITLE
Gdown Error Missing

### ISSUE THREAD

**Issue by VeLuisS** [YoungFellow-le/photoshop-22-linux#14]
Hello, I have problems when starting the installation, it happens that it gives me an error when verifying the gdown. I have already installed it using the command you specify, but it keeps giving the same error.

`gdown is MISSING! (To install: "pip3 install gdown")

- ERROR: Please install the missing dependencies and then reattempt the isntallation
`

`$ pip3 install gdown
Requirement already satisfied: gdown in /home/MXLinux/.local/lib/python3.9/site-packages (4.5.3)
Requirement already satisfied: filelock in /home/MXLinux/.local/lib/python3.9/site-packages (from gdown) (3.8.0)
Requirement already satisfied: tqdm in /home/MXLinux/.local/lib/python3.9/site-packages (from gdown) (4.64.1)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from gdown) (1.16.0)
Requirement already satisfied: requests[socks] in /home/MXLinux/.local/lib/python3.9/site-packages (from gdown) (2.28.1)
Requirement already satisfied: beautifulsoup4 in /home/MXLinux/.local/lib/python3.9/site-packages (from gdown) (4.11.1)
Requirement already satisfied: soupsieve>1.2 in /home/MXLinux/.local/lib/python3.9/site-packages (from beautifulsoup4->gdown) (2.3.2.post1)
Requirement already satisfied: certifi>=2017.4.17 in /home/MXLinux/.local/lib/python3.9/site-packages (from requests[socks]->gdown) (2022.9.24)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/MXLinux/.local/lib/python3.9/site-packages (from requests[socks]->gdown) (1.26.12)
Requirement already satisfied: charset-normalizer<3,>=2 in /home/MXLinux/.local/lib/python3.9/site-packages (from requests[socks]->gdown) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /home/MXLinux/.local/lib/python3.9/site-packages (from requests[socks]->gdown) (3.4)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /home/MXLinux/.local/lib/python3.9/site-packages (from requests[socks]->gdown) (1.7.1)
`

### System info:
 - **Linux distrobution:** MX Linux (Basada en Ubuntu version final)
 - **Desktop environment:** KDE
 - **Wine version:** 6

**Comment by PhpOfc** [comment]
what distro are you at? i had the same error also, pq i installed gdown via the AUR https://aur.archlinux.org/packages/gdown

**Comment by VeLuisS** [comment]
> en que distro estás? También tuve el mismo error, pq instalé gdown a través del AUR y funcionó. https://aur.archlinux.org/packages/gdown

I use one based on Ubuntu/Debian. AUR I think is for Arch distributions

**Comment by VeLuisS** [comment]
I got it, manually moved the file to /usr/local/bin/ and it worked.
It is now in the installation process.

**Comment by darrylmorley** [comment]
> I got it, manually moved the file to /usr/local/bin/ and it worked. It is now in the installation process.

Which file did you move?

**Comment by YoungFellow-le** [comment]
> @VeLuisS Which file did you move please?

I think it's this file:
```
/home/`whoami`/.local/bin/gdown
```
