### ISSUE TITLE
Can't launch photoshop

### ISSUE THREAD

**Issue by unicornsandcandies** [YoungFellow-le/photoshop-22-linux#16]
photoshop is showing me error when launching. It worked flawlessly before but I needed to unistall it for a while.
![2022-12-08_00-47](https://user-images.githubusercontent.com/112720004/206313933-92a0a441-9c7f-41ad-87f7-5f81944a8133.png)

there's a log:
https://pastebin.com/raw/G9ur9SRj

**Comment by unicornsandcandies** [comment]
I tried changing wine and installing everything in newest version possible. Now there's similar error. There's a log:

Unhandled exception: page fault on execute access to 0x0000000000000000 in 64-bit code (0x0000000000000000).
Register dump:
 rip:0000000000000000 rsp:000000000011d098 rbp:00000003592ec3d0 eflags:00010246 (  R- --  I  Z- -P- )
 rax:000000000084d180 rbx:0000000000865860 rcx:000000007f1ffe60 rdx:000000000011d0c0
 rsi:00000000008648a0 rdi:00000000008648a0  r8:000000007f1ffe60  r9:0000000000000000 r10:00007ffce1f7e170
 r11:00007ffce1f7e1b0 r12:0000000000894ea0 r13:0000000000894a10 r14:000000000011d620 r15:0000000000000000
Stack dump:
0x000000000011d098:  000000035913a10b 0000000500000007
0x000000000011d0a8:  ffffffffffffffff 000000007f1ffd30
0x000000000011d0b8:  0000000000000001 000000003b9f9493
0x000000000011d0c8:  0000000000000000 0000000000000000
0x000000000011d0d8:  0000000000000000 0000000000000000
0x000000000011d0e8:  0000000000000000 0000000000000001
0x000000000011d0f8:  0000000000895210 00000003592ec3d0
0x000000000011d108:  0000000000864880 000000000011d1a8
0x000000000011d118:  00000003590de64c 000000000011d410
0x000000000011d128:  0000000100849a98 0000000000000000
0x000000000011d138:  0100010000000000 0000000100000000
0x000000000011d148:  0000000000000001 0000000000864880
Backtrace:
=>0 0x0000000000000000 (0x00000003592ec3d0)
0x0000000000000000: -- no code accessible --
Modules:
Module	Address					Debug info	Name (90 modules)
PE	0000000000250000-000000000032a000	Deferred        chrome_elf
PE	0000000002530000-0000000002981000	Deferred        d3dcompiler_47
PE	0000000002990000-0000000002e9c000	Deferred        libglesv2
PE	0000000002ea0000-0000000002ebf000	Deferred        libegl
PE	000000007b000000-000000007b3f3000	Deferred        kernelbase
PE	000000007b600000-000000007b963000	Deferred        kernel32
PE	0000000140000000-000000014011e000	Deferred        adobe spaces helper
PE	0000000170000000-000000017031f000	Deferred        ntdll
PE	0000000180000000-00000001868c5000	Deferred        libcef
PE	00000001c4ee0000-00000001c4fb4000	Deferred        winspool
PE	00000001c69e0000-00000001c776f000	Deferred        shell32
PE	00000001c8b40000-00000001c8bb6000	Deferred        msacm32
PE	00000001c8db0000-00000001c90c9000	Deferred        msvcrt
PE	00000001cfdf0000-00000001cfe56000	Deferred        dxva2
PE	00000001d97a0000-00000001d97ae000	Deferred        api-ms-win-core-fibers-l1-1-1
PE	00000001dd3f0000-00000001dd765000	Deferred        crypt32
PE	00000001ec2b0000-00000001ec350000	Deferred        ws2_32
PE	00000001f51e0000-00000001f5212000	Deferred        hid
PE	00000001fedf0000-00000001fee0c000	Deferred        api-ms-win-crt-private-l1-1-0
PE	0000000201cf0000-0000000201d94000	Deferred        secur32
PE	000000020fc60000-000000020fe8f000	Deferred        mf
PE	000000021a7e0000-000000021a9ce000	Deferred        setupapi
PE	0000000226310000-000000022631e000	Deferred        api-ms-win-core-string-l1-1-0
PE	0000000228450000-00000002284c6000	Deferred        propsys
PE	0000000231ae0000-0000000231d6c000	Deferred        rpcrt4
PE	000000023d820000-000000023e0d1000	Deferred        user32
PE	0000000240030000-00000002400bd000	Deferred        iphlpapi
PE	000000024f470000-000000024f4d4000	Deferred        mpr
PE	00000002522e0000-00000002523cd000	Deferred        oleacc
PE	000000025d740000-000000025d75f000	Deferred        dwmapi
PE	0000000262250000-0000000262260000	Deferred        api-ms-win-crt-runtime-l1-1-0
PE	000000026b4c0000-000000026b756000	Deferred        gdi32
PE	000000026ed50000-000000026ed6b000	Deferred        vcruntime140
PE	0000000270f60000-0000000271269000	Deferred        d3d9
PE	00000002739c0000-0000000273ed2000	Deferred        oleaut32
PE	0000000274a50000-0000000274a77000	Deferred        kerberos
PE	000000027ab80000-000000027ab92000	Deferred        cfgmgr32
PE	000000028ba60000-000000028ba6e000	Deferred        api-ms-win-crt-time-l1-1-0
PE	000000028dfa0000-000000028dfbf000	Deferred        nsi
PE	000000029cfc0000-000000029d008000	Deferred        dnsapi
PE	000000029ea80000-000000029ea8e000	Deferred        api-ms-win-core-datetime-l1-1-1
PE	00000002a4090000-00000002a40c0000	Deferred        wtsapi32
PE	00000002a9540000-00000002a954f000	Deferred        usp10
PE	00000002bb750000-00000002bbcaf000	Deferred        comctl32
PE	00000002d23f0000-00000002d2437000	Deferred        credui
PE	00000002d4d40000-00000002d4d91000	Deferred        bcrypt
PE	00000002e3540000-00000002e364f000	Deferred        shlwapi
PE	00000002e8f10000-00000002e949e000	Deferred        ole32
PE	00000002edf00000-00000002ee12e000	Deferred        dxgi
PE	00000002f1fa0000-00000002f1fbe000	Deferred        version
PE	00000002f7f20000-00000002f7f2c000	Deferred        vcruntime140_1
PE	00000002fa030000-00000002fa03e000	Deferred        api-ms-win-core-localization-obsolete-l1-2-0
PE	000000030a2c0000-000000030a2d0000	Deferred        api-ms-win-crt-stdio-l1-1-0
PE	000000030a950000-000000030ac4e000	Deferred        dwrite
PE	000000030c980000-000000030c98f000	Deferred        api-ms-win-core-synch-l1-2-0
PE	00000003126f0000-0000000312745000	Deferred        shcore
PE	0000000316370000-0000000316382000	Deferred        psapi
PE	000000031f800000-000000031fa59000	Deferred        comdlg32
PE	0000000327020000-00000003271ac000	Deferred        combase
PE	000000032a700000-000000032a7c1000	Deferred        sechost
PE	0000000330260000-000000033038f000	Deferred        advapi32
PE	0000000335260000-0000000335296000	Deferred        rtworkq
PE	000000033ea00000-000000033ea10000	Deferred        api-ms-win-crt-string-l1-1-0
PE	00000003422e0000-0000000342609000	Deferred        urlmon
PE	0000000346ba0000-0000000346beb000	Deferred        jsproxy
PE	0000000351680000-000000035168f000	Deferred        api-ms-win-core-localization-l1-2-1
PE	0000000355100000-000000035510e000	Deferred        api-ms-win-crt-locale-l1-1-0
PE	0000000358120000-0000000358247000	Deferred        winhttp
PE	0000000359050000-00000003593d5000	Deferred        d3d11
PE	0000000360a80000-0000000360a91000	Deferred        api-ms-win-crt-math-l1-1-0
PE	0000000360e10000-0000000360e9d000	Deferred        msvcp140
PE	00000003673d0000-0000000367480000	Deferred        netapi32
PE	0000000375610000-000000037566c000	Deferred        win32u
PE	00000003785e0000-00000003785f3000	Deferred        vulkan-1
PE	00000003871c0000-000000038720e000	Deferred        concrt140
PE	0000000388e20000-0000000388e4b000	Deferred        userenv
PE	000000039b510000-000000039b51f000	Deferred        api-ms-win-crt-heap-l1-1-0
PE	000000039c380000-000000039c3c1000	Deferred        msv1_0
PE	00000003a0440000-00000003a06ab000	Deferred        wininet
PE	00000003a19e0000-00000003a19fe000	Deferred        ncrypt
PE	00000003a37f0000-00000003a380c000	Deferred        dcomp
PE	00000003a6d40000-00000003a6f3e000	Deferred        mfplat
PE	00000003aa4c0000-00000003aa4df000	Deferred        dhcpcsvc
PE	00000003af670000-00000003afa00000	Deferred        ucrtbase
PE	00000003afd00000-00000003afd68000	Deferred        imm32
PE	00000003b6dc0000-00000003b6e80000	Deferred        winevulkan
PE	00000003b8f00000-00000003b90b3000	Deferred        winmm
PE	00000003bb250000-00000003bb3db000	Deferred        cryptui
PE	00000003be590000-00000003be85b000	Deferred        dbghelp
PE	00007f2e91f70000-00007f2e91f74000	Deferred        winex11
Threads:
process  tid      prio (all id:s are in hex)
00000038 services.exe
	0000003c    0
	00000040    0
	0000004c    0
	0000005c    0
	00000070    0
	000000a8    0
	000000c4    0
	000000dc    0
00000044 winedevice.exe
	00000048    0
	00000054    0
	00000058    0
	00000060    0
	00000064    0
	000000d0    0
00000068 winedevice.exe
	0000006c    0
	00000074    0
	00000078    0
	0000007c    0
	00000088    0
	0000008c    0
	00000090    0
00000094 plugplay.exe
	00000098    0
	000000b0    0
	000000b4    0
	000000b8    0
	00000370    0
	00000374    0
000000bc svchost.exe
	000000c0    0
	000000c8    0
	000000cc    0
000000d4 rpcss.exe
	000000d8    0
	000000e0    0
	000000e4    0
	000000e8    0
	000000ec    0
	00000244    0
	00000388    0
	00000390    0
0000021c start.exe
	00000220    0
00000224 conhost.exe
	00000228    0
0000022c photoshop.exe
	00000230    0
	00000254    0
	00000258    0
	0000025c    0
	00000260    0
	00000264    0
	0000026c    0
	00000294    0
	00000298    0
	0000029c    0
	000002a0    0
	000002a4    1
	000002b8    0
	000002bc    0
	000002c0    0
	000002c4    0
	000002c8    0
	000002cc    0
	000002d0    0
	000002d4    0
	000002d8    0
	000002dc    0
	000002e0    0
	000002e4    0
	000002e8    0
	000002ec    0
	000002f0    0
	000002f4    0
	000002f8    0
	000002fc    0
	00000304    0
	00000308    0
	0000030c    0
	00000310    0
	00000314    0
	00000318   -2
	0000031c   -2
	00000320    0
	00000324    0
	00000328    0
	0000032c    0
	00000330   -2
	00000334    0
	00000338    0
	0000033c   -2
	00000340    0
	00000344    0
	00000348    0
	0000034c    0
	00000358    0
	0000035c    0
	00000360    0
	00000364    0
	00000368   -2
	0000036c    0
	00000378    0
	00000384    0
	000003c8    0
	00000414    0
	00000454    0
	00000458    0
	0000045c    0
	00000460    0
00000234 explorer.exe
	00000238    0
	0000023c    0
	00000240    0
00000350 (D) C:\Program Files\Adobe\Adobe Photoshop 2021\Required\Plug-ins\Spaces\Adobe Spaces Helper.exe
	00000354    0 <==
	00000394    0
	00000398    0
	000003d8    0
	000003dc    0
	000003e0    0
	000003e4    0
	000003e8    0
	000003ec    0
	000003f0   -2
	000003f4   -2
	000003f8    0
	000003fc    0
	00000400    0
	00000404   -2
	00000408    0
	0000044c    0
0000037c Adobe Spaces Helper.exe
	00000380    0
	0000039c    0
	000003a0    0
	000003a4    0
	000003a8    0
	000003ac   -2
	000003b0   -2
	000003b4    0
	000003b8    0
	000003bc    0
	000003c0    0
	000003c4    0
	000003cc    0
	000003d0    0
	000003d4   -2
0000040c Adobe Spaces Helper.exe
	00000410    0
	00000424    0
	00000428    0
	0000042c    0
	00000430    0
	00000434   -2
	00000438   -2
	0000043c    0
	00000440    0
	00000444    0
	00000448    0
	00000450    0
00000468 Adobe Spaces Helper.exe
	0000046c    0
	00000470    0
	00000474    0
	00000478    0
	0000047c    0
	00000480    0
	00000484   -2
	00000488   -2
	0000048c    0
	00000490    0
	00000494    0
	00000498   -2
System information:
    Wine build: wine-7.0.1
    Platform: x86_64
    Version: Windows 10
    Host system: Linux
    Host version: 5.15.0-56-generic

**Comment by unicornsandcandies** [comment]
![2022-12-08_00-58](https://user-images.githubusercontent.com/112720004/206323061-90caa88d-5544-4d4e-a107-72667905a777.png)

**Comment by YoungFellow-le** [comment]
Please try updating `wine` to the latest version, and then try reinstalling Photoshop

**Comment by unicornsandcandies** [comment]
> Please try updating `wine` to the latest version, and then try reinstalling Photoshop

I have latest version I could install following their website (wine-7.0.1)

There's tutorial I followed:
https://wiki.winehq.org/Ubuntu

**Comment by YoungFellow-le** [comment]
Okay,
1. Did you install `vk3d`? (Did you choose 'y' or 'n' at this prompt)
```
Would you like to install Adobe Camera Raw at the end?
(y/n):
```
2. Can you post some sort of system info, like the output of `inxi -S` (if you have `inxi` installed)

**Comment by unicornsandcandies** [comment]
> Okay,
> 
>     1. Did you install `vk3d`? (Did you choose 'y' or 'n' at this prompt)
> 
> 
> ```
> Would you like to install Adobe Camera Raw at the end?
> (y/n):
> ```
> 
>     2. Can you post some sort of system info, like the output of `inxi -S` (if you have `inxi` installed)

Yes, I installed both camera raw and vk3d

There's output of inxi:

>> inxi -S           
System:                                               
  Host: stefa-laptok                                  
    Kernel: 5.15.0-56-generic x86_64 bits: 64         
    Console: pty pts/2                                
    Distro: Ubuntu 22.04.1 LTS (Jammy Jellyfish)

**Comment by YoungFellow-le** [comment]
Okay, thanks a lot.
Can you try to install it without `vk3d`, and see if that makes a difference.

**Comment by unicornsandcandies** [comment]
> Okay, thanks a lot. Can you try to install it without `vk3d`, and see if that makes a difference.
thats what I have now:

bash -c '/home/stefa/fotoszop/photoshop-22-linux/scripts/launcher.sh'

0100:err:module:import_dll Library d3d12.dll (which is needed by L"C:\\Program Files\\Adobe\\Adobe Photoshop 2021\\photoshop.exe") not found
0100:err:module:LdrInitializeThunk Importing dlls for L"C:\\Program Files\\Adobe\\Adobe Photoshop 2021\\photoshop.exe" failed, status c0000135

**Comment by YoungFellow-le** [comment]
The new error says that Photoshop cant be found.
I'm sorry for these issues you're facing.
Can you update the repo by running: `git pull`
And then run the installer again.
Once the installation has completed, can you post the `logs/installer.log` file.

**Comment by unicornsandcandies** [comment]
> The new error says that Photoshop cant be found. I'm sorry for these issues you're facing. Can you update the repo by running: `git pull` And then run the installer again. Once the installation has completed, can you post the `logs/installer.log` file.

now I can't even start main-menu.sh 

>-------------- Adobe Photoshop CC 2021 (v22)  installer main menu on Linux --------------

/home/stefa/fotoszop/photoshop-22-linux/main-menu.sh: line 90: unexpected EOF while looking for matching `"'
/home/stefa/fotoszop/photoshop-22-linux/main-menu.sh: line 93: syntax error: unexpected end of file

**Comment by YoungFellow-le** [comment]
I'm so sorry :facepalm:, I just fixed it now.

**Comment by unicornsandcandies** [comment]
https://logpaste.com/fw4ADRik

**Comment by YoungFellow-le** [comment]
Okay, and what is the output when you run Photoshop?
```sh
bash -c '/home/stefa/fotoszop/photoshop-22-linux/scripts/launcher.sh'
```

**Comment by vagnerlandio** [comment]
I had the same issue using wine 6. Updating wine to the latest version (7 or 8) solved my problem and now the photoshop run without issues

**Comment by YoungFellow-le** [comment]
I will close this now.
If you need more help @unicornsandcandies, then feel free to reopen this issue.
