### ISSUE TITLE
it doesn't launch

### ISSUE THREAD

**Issue by HoxyAnime** [YoungFellow-le/photoshop-22-linux#6]
I have that message when I execute launcher.sh
./launcher.sh 
./launcher.sh: línea 2: cd: /home/hoxy2/photoshop-22-linux/Ps-prefix/drive_c/Program Files/Adobe/Adobe Photoshop 2021/: No existe el archivo o el directorio
0009:err:module:__wine_process_init L"C:\\windows\\system32\\photoshop.exe" not found

what can it be?

**Comment by YoungFellow-le** [comment]
Please reopen this issue, and fill in the bug report information provided by the template.
